### PR TITLE
Undo es6 module setup

### PR DESCRIPTION
**Pull request by JSAssassin**

### CODE REVIEW

**Comment by dlongley** [comment]
Has this been tested in browsers and also backend code with the necessary versions of node? I'm a little surprised that it would work in node given that it's using ESM syntax at a `CommonJS` entry point without any signals in the package.json that it's an ESM module, etc.

**Comment by dlongley** [comment]
Maybe some `test-node` script should be added here to CI to avoid this problem in the future.

**Comment by mattcollier** [comment]
> Maybe some `test-node` script should be added here to CI to avoid this problem in the future.

Yes, I see there is no nodejs test suite here at all.  +1 for creating one.

That said, I thought it was the case that `bedrock-web` modules were limited to front end use.  Has that convention changed?

**Comment by dlongley** [comment]
> That said, I thought it was the case that bedrock-web modules were limited to front end use. Has that convention changed?

bedrock-web* modules are "web first" not "web only". So they are implemented to run against Web APIs -- but if those APIs are available in node.js (or there are polyfills present), the modules should work there as well. This is especially helpful for creating headless CLI tools that perform the same / similar tasks to Web apps.

**Review by dlongley — CHANGES_REQUESTED** [review]
Marking as changes requested to enable a new review request once the changes are in.

**Comment by JSAssassin** [comment]
@dlongley So I tested this on nodejs projects, it doesn't work. Is the ask here that I should setup esm here so it will work on both browser and backend code? (I thought we were moving away from esm, right?)

**Comment by dlongley** [comment]
@JSAssassin, we are moving away from using the `esm` lib -- but this does need to work with node.js projects. @davidlehn -- we need you to weigh in here on what to do. It may be that we just need to add `esm` for now and then remove it later. I don't understand how this package was working with node.js projects before if the `esm` lib was never used.

**Comment by JSAssassin** [comment]
Closing. This is no longer relevant.

**Pull request closed without merging**
